DELETE FROM dbo.MarkScheme
WHERE MARKSCHEMEASSIGNMENTID = '6'

DELETE FROM dbo.LabGroup
WHERE LABGROUPASSIGNMENTID = '6'

DELETE FROM dbo.MarkSchemeSection
WHERE SECTIONASSIGNMENTID = '6'

DELETE FROM dbo.MarkSchemePart
WHERE PARTASSIGNMENTID = '6'